name: lovelivemusicplayer
description: 一款专属于LLer的移动播放器

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.4.9+49

environment:
  sdk: ">=2.17.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  get: ^4.6.6
  flutter_spinkit: ^5.2.0
  dio: ^5.4.1 # 网络加载
  path_provider: ^2.1.2 # 路径提供
  pull_to_refresh:  # 下拉刷新上拉加载
    git:
      url: https://gitee.com/zhushenwudi/flutter_pulltorefresh
      ref: 6d7fbdd
  web_socket_channel: ^2.4.4 # webSocket
  connectivity_plus: ^5.0.2 # 网络监测
  scan: ^1.6.0 # 扫码
  flutter_smart_dialog: ^4.9.6 # 弹窗
  synchronized: ^3.1.0+1 # 锁
  get_storage: ^2.1.1 # sp存储
  common_utils: ^2.1.0 # 工具类
  flutter_screenutil: ^5.9.0 # 屏幕适配方案
  we_slide: ^2.4.0 # 播放器屏幕操作组件
  flutter_native_splash: ^2.3.13 # 启动页
  marquee_text: # 走马灯滚动文字
    git:
      url: https://gitee.com/zhushenwudi/flutter-marquee-text
      ref: 015bdeb
  flutter_svg: ^2.0.9 # svg图片支持
  just_audio: # 音频播放
    git:
      url: https://github.com/zhushenwudi/just_audio
      path: just_audio
      ref: 04b870e
  just_audio_background: ^0.0.1-beta.11 # 音频播放后台服务
  event_bus: ^2.0.0 # 事件总线通信
  floor: ^1.4.2 # 数据库服务
  flutter_staggered_grid_view: ^0.7.0 # 分栏列表
  concurrent_queue: ^1.4.0 # 队列
  wakelock: ^0.6.2 # 屏幕常亮
  flutter_image_compress: # 图片压缩
    git:
      url: https://github.com/zhushenwudi/flutter_image_compress
      path: packages/flutter_image_compress
  cached_network_image: # 网络图片缓存库
    git:
      url: https://github.com/zhushenwudi/flutter_cached_network_image
      path: cached_network_image
  color_thief_flutter: # 取色器
    git:
      url: https://gitee.com/zhushenwudi/color_thief_flutter
      ref: e9da75b
  log4f: ^0.0.3 # 日志
  device_info_plus: ^9.1.2 # 设备信息
  flutter_lyric: ^2.0.4+6 # 歌词显示
  flutter_app_update: ^3.0.4 # 版本升级
  flutter_sticky_header: ^0.6.5 # 粘性头
  url_launcher: ^6.2.4 # url跳转
  image_picker: ^1.0.7 # 图片选择
  croppy: # 图片裁切
    git:
      url: https://github.com/zhushenwudi/croppy
      ref: master
  colorful_safe_area: ^1.0.0 # 定制safe_area
  open_appstore: # 跳转到应用商店
    git:
      url: https://github.com/zhushenwudi/flutter_open_appstore
      ref: master
  mobcommonlib: ^1.1.5 # MobTech库
  sharesdk_plugin: ^1.3.10 # MobTech分享插件
  crypto: ^3.0.3 # 加密
  flutter_inappwebview: ^6.0.0 # WebView
  flexible_scrollbar: # 滚动条
    git:
      url: https://github.com/zhushenwudi/flexible_scrollbar
      ref: master
  flutter_carplay: # Carplay支持
    git:
      url: https://github.com/zhushenwudi/flutter_carplay
      ref: combine-all
  sentry_flutter: ^7.16.1 # Sentry
  scrolls_to_top: ^2.1.1 # 滚动到顶部
  haptic_feedback: ^0.4.2 # 震动
  umeng_push_sdk: ^2.2.0 # 友盟推送

dependency_overrides:
  md5_file_checksum:
    git:
      url: https://github.com/zhushenwudi/md5_file_checksum
      ref: main
  win32: ^5.2.0
  web: ^0.5.0
  js: ^0.7.1
  uuid: ^4.3.3 # 唯一码

dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^1.4.2
  build_runner: ^2.4.8

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/main/
    - assets/drawer/
    - assets/player/
    - assets/tab/
    - assets/dialog/
    - assets/sync/
    - assets/logo/
    - assets/tachie/
    - assets/role/
    - assets/drive/
    - assets/launch/
    - shorebird.yaml

  fonts:
    - family: KaTong
      fonts:
        - asset: assets/fonts/KaTong.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
