const Map<String, String> en_US = {
  'music': 'Music',
  'album': 'Album',
  'singer': 'Singer',
  'iLove': 'Love',
  'songMenu': 'Menu',
  'history': 'History',
  'update_fail': 'Update failed',
  'update': 'Update',
  'update_yes': 'Yes',
  'update_no': 'No',
  'no_need_update': 'The current version is the latest',
  'need_jump_to_app_store': 'Check it out in the app store',
  'music_trans': 'Transfer songs',
  'data_sync': 'Data sync',
  'theme_with_system': 'Theme with os',
  'colorful_mode': 'Colorful mode',
  'splash_photo': 'Splash photo',
  'fetch_songs': 'Fetch songs',
  'clear_database': 'Clear databases',
  'will_shutdown': 'App will shutdown, please turn it on by yourself',
  'clean_success': 'Clean up successfully',
  'view_log': 'View logs',
  'privacy_agreement': 'Privacy Agreement',
  'night_mode': 'Night mode',
  'downloading': 'Downloading data',
  'now_is_latest': 'It is the latest version. Do you want to overwrite it?',
  'data_error': 'Data error',
  'fetch_songs_fail': 'Fetch songs error',
  'importing': 'Importing...',
  'transferring': 'Transferring...',
  'loading': 'Loading...',
  'song_lib': 'SongLib',
  'mine': 'Mine',
  'requesting': 'Requesting...',
  'please_check_network': 'Please check network',
  'keep_same_lan': 'Keep your phone and computer on the same LAN',
  'keep_screen_and_scan_qr':
      'Keep the screen steady on and scan the QR code on the PC',
  'phone2pc': 'Phone >> PC',
  'pc2phone': 'PC >> Phone',
  'device_pair': 'Device pairing',
  'terminate_trans':
      'The connection and transmission will be interrupted. Do you want to continue?',
  'confirm': 'Confirm',
  'connect_fail': 'Connection failed',
  'album_info': 'Album info',
  'add_success': 'Add successfully',
  'add_fail': 'Add failed',
  'add_to_playlist': 'Add to a playlist',
  'add_to_menu': 'Add to a song menu',
  'create_menu': 'Create a song menu',
  'create_success': 'Create successfully',
  'create_over_max': 'Exceeding the maximum quantity',
  'add_to_iLove': 'Add to i love successfully',
  'remove_from_iLove': 'Remove from i love successfully',
  'rename_menu': 'Rename menu',
  'delete_menu': 'Delete menu',
  'music_info': 'Music info',
  'view_album': 'View album',
  'remove_music': 'remove this song',
  'shuffle_play': 'Shuffle play',
  'order_play': 'Order play',
  'single_play': 'Single play',
  'total_number_unit': 'song(s)',
  'total_album_number_unit': 'album(s)',
  'duration': 'Duration',
  'position': 'Position',
  'release_date': 'Release date',
  'classification': 'Classification',
  'unknown': 'unknown',
  'select_items': 'Selected',
  'cancel': 'Cancel',
  'click_again_to_back': 'Click again to return to the desktop',
  'data_parsing': 'Data parsinging...',
  'github_url': 'Open source project link of this software',
  'no_songs': 'No songs',
  'no_lyrics': 'No lyrics',
  'title': 'Title',
  'message': 'Message',
  'input_menu_name': 'Please input menu name',
  'privacy_policy': 'Privacy policy',
  'permission_show_full': 'View full version',
  'permission_main_message':
      'Welcome to LoveLiveMusicPlayer!\n\nWe will use the User Agreement and Privacy Policy to help you understand the services provided by the software for you and the way you collect and process your personal data.\nClick the "Agree and Continue" button to indicate that you have agreed.',
  'permission_external_link': 'User Agreement and Privacy Policy',
  'permission_agree': 'Agree and continue',
  'permission_disagree': 'Disagree and shutdown',
  'no_data': 'No data',
  'choose_your_clean_data': 'Please select the data to be cleaned',
  'remove_songs_data': 'Remove songs data',
  'remove_user_data': 'Remove user data',
  'explain_songs_data': 'Song data: cached songs data',
  'explain_user_data': 'User data: player configuration, love, playlist',
  'resetting': 'Resetting',
  'warning_choose': 'Warning: Please choose carefully!',
  'confirm_full_trans': 'Are you sure to completely cover the data?',
  'cover_full_data': 'Completely cover the data',
};
