const Map<String, String> jaJP = {
  'music': '曲',
  'album': 'アルバム',
  'music_name': '曲名',
  'singer': '歌手',
  'iLove': '私の好き',
  'songMenu': 'プレイリスト',
  'history': '最近の再生',
  'update_fail': '更新に失敗しました',
  'update': 'バージョンアップ',
  'update_yes': 'アップグレード',
  'update_no': 'アップグレードしない',
  'no_need_update': '現在最新バージョンです',
  'music_trans': '曲の転送',
  'data_sync': 'データ同期',
  'theme_with_system': 'システムに従う',
  'colorful_mode': 'カラフルモード',
  'splash_photo': 'スプラッシュ画像',
  'enable_background_photo': '背景画像を有効にする',
  'choose_background_photo': '背景画像を選択',
  'fetch_songs': 'データ更新',
  'clear_database': 'データをクリア',
  'will_shutdown': 'アプリがもうすぐ終了します。手動で再起動してください',
  'clean_success': 'クリア成功',
  'view_log': 'ログを見る',
  'privacy_agreement': 'プライバシー契約',
  'system_settings': 'システム設定',
  'drive_mode': 'ドライブモード',
  'night_mode': 'ナイトモード',
  'downloading': 'データをダウンロード中',
  'now_is_latest': '最新バージョンです。上書きしますか？',
  'data_error': 'データ異常',
  'fetch_songs_fail': 'データソースの取得に失敗しました',
  'importing': 'インポート中...',
  'transferring': '転送中...',
  'loading': '読み込み中...',
  'song_lib': '曲ライブラリ',
  'mine': 'マイ',
  'requesting': 'ネットワークをリクエスト中...',
  'please_check_network': 'ネットワークを確認してください',
  'keep_same_lan': 'スマートフォンとPCが同じローカルネットワークにいることを確認してください',
  'keep_screen_and_scan_qr': '画面を常にオンにして、PCのQRコードをスキャンしてください',
  'phone2pc': 'スマホ ≫ PC',
  'pc2phone': 'PC ≫ スマホ',
  'device_pair': 'デバイスペアリング',
  'terminate_trans': '終了すると接続と転送が中断されます。続行しますか？',
  'confirm': '確認',
  'connect_fail': '接続に失敗しました',
  'album_info': 'アルバム情報',
  'add_success': '追加成功',
  'add_fail': '追加失敗',
  'add_to_playlist': 'プレイリストに追加',
  'add_to_menu': 'プレイリストに追加',
  'create_menu': 'プレイリストを作成',
  'create_success': '作成成功',
  'create_over_max': '最大数を超えました',
  'add_to_iLove': '私の好きに追加しました',
  'remove_from_iLove': '私の好きから削除しました',
  'rename_menu': 'プレイリストの名前を変更',
  'delete_menu': 'プレイリストを削除',
  'music_info': '曲情報',
  'view_album': 'アルバムを見る',
  'remove_music': '曲を削除',
  'shuffle_play': 'シャッフル再生',
  'order_play': '順番再生',
  'single_play': '単曲リピート',
  'total_number_unit': '曲',
  'total_album_number_unit': 'アルバム',
  'duration': '長さ',
  'position': '位置',
  'release_date': '発売日',
  'classification': '分類',
  'unknown': '不明',
  'select_items': '選択済み',
  'cancel': 'キャンセル',
  'click_again_to_back': 'もう一度クリックしてデスクトップに戻る',
  'data_parsing': 'データ解析中...',
  'github_url': 'このソフトウェアのオープンソースプロジェクトリンク',
  'no_songs': '曲がありません',
  'no_lyrics': '歌詞がありません',
  'title': 'タイトル',
  'message': 'メッセージ',
  'input_menu_name': 'プレイリスト名を入力してください',
  'privacy_policy': 'プライバシー保護方針',
  'permission_show_full': '完全版を表示',
  'permission_main_message':
      'LoveLiveMusicPlayerをご利用いただきありがとうございます！\n\nユーザー契約及びプライバシーポリシーを通じて、本ソフトウェアが提供するサービスや、個人データの収集・処理方法についてご理解いただけます。\n「同意して続行」ボタンをクリックすることで、同意したことになります。',
  'permission_external_link': '《ユーザー契約及びプライバシーポリシー》',
  'permission_agree': '同意して続行',
  'permission_disagree': '同意しない',
  'no_data': 'データがありません',
  'choose_your_clean_data': 'クリアするデータを選択してください',
  'remove_songs_data': '曲データを削除',
  'remove_user_data': 'ユーザーデータを削除',
  'explain_songs_data': '曲データ：曲のキャッシュデータ',
  'explain_user_data': 'ユーザーデータ：プレイヤー設定、私の好き、プレイリスト',
  'resetting': 'リセット中...',
  'warning_choose': '警告: 注意して選択してください',
  'confirm_full_trans': 'データを完全に上書きしますか',
  'cover_full_data': 'データを完全に上書き',
  'file_path_error': 'ファイルパスエラー',
  'crop_background_image': '背景画像をトリミング',
  'copy_success': 'コピー成功',
  'need_enable_bg': 'まず背景画像を有効にしてください',
  'search_lyric': '歌詞を再検索',
  'search_lyric_success': '歌詞取得成功',
  'search_lyric_failed': '歌詞取得失敗',
  'share_app': 'あなたにLLMPを共有しました',
  'outer_share_music': 'あなたに曲を共有しました',
  'outer_share_menu': 'あなたにプレイリストを共有しました',
  'share_music': '曲を共有',
  'share_menu': 'プレイリストを共有',
  'no_qq': 'TIM/QQがインストールされていません',
  'version_incompatible': 'APPとPCバージョンが互換性がありません。ブログに行って更新してください',
  'no_found_music1': 'この曲が見つかりません',
  'need_play_share_music': '共有曲を再生しますか',
  'no_found_music2': '利用可能な曲が見つかりません',
  'need_import_share_menu': '共有プレイリストをインポートしますか',
  'delete_from_menu': 'プレイリストから削除',
  'confirm_delete_from_menu': '選択した曲をプレイリストから削除しますか？',
  'cancel_i_like': '私の好きをキャンセル',
  'confirm_to_delete_music': '選択した曲を私の好きから削除しますか？',
  'share': 'アプリを共有',
  'skip': 'スキップ',
  'net_error': 'ネットワークエラー',
  'hint': 'ヒント',
  'use_http_music': 'HTTP音楽ライブラリを使用',
  'input_http_url': 'HTTPアドレスを入力',
  'support_http_characters': 'サポートされている文字: a-z A-Z 0-9 .:/_-',
  'now_can_not_play': '現在再生できません',
  'moe_girl_wiki': '萌娘百科',
  'need_delete_menu': 'プレイリストを削除しますか',
  'select_time': '時間を選択してください（単位：分）',
  'upgrading': 'アップグレード中...',
  'upgrade_on_next_time': '更新は次回起動時に有効になります',
  'end_time': '終了時間：',
  'timed_to_stop': '定時停止',
  'timed_to_stop_remain': '定時停止まで残り',
  'minutes': '分',
  'please_give_install_permission_manual': 'APKのインストール権限を手動で付与してください',
  'please_give_install_permission':
      'アップグレードにはAPKのインストール権限を付与する必要があります。権限を付与しますか？',
  'privacy_detail1': '''親愛なるLLer：

「ソフトウェア使用許諾契約」（以下「本契約」）に記載されたすべての権利および制限を必ずお読みください。契約条件に同意しない限り、本ソフトウェアおよびその関連サービスを使用する権利はありません。本ソフトウェアを使用することにより、契約に同意したものとみなされます。

1. 権利声明
本ソフトウェアはオープンソースプロジェクトであり、著作権は作者zhushenwudiに帰属します。
一部の情報はネットワークリソースから取得されており、テキスト表現やその組み合わせ、アイコン、画像、色、関連データなどが含まれます。著作権の問題が発生した場合は、作者のメール55681140@163.comに連絡して削除または置き換えを依頼してください。
本ソフトウェアの宣伝や関連ファイルの転載については、作者に連絡して許可を得てください。使用中に発生した問題については、作者に連絡してサポートを受けることができます。作者はユーザーに本ソフトウェアの修正やアップグレード版を提供する権利を留保します。

2. 许可范围
ダウンロード、インストール、使用：ユーザーは非商業目的で無制限に本ソフトウェアをダウンロード、インストール、使用できます。
コピー、配布、伝播：ユーザーは非商業目的で無制限に本ソフトウェアをコピー、配布、伝播できますが、各コピー、配布、伝播が本ソフトウェアのすべてのソフトウェア、電子文書、著作権、商標を含む完全かつ真実であることを保証しなければなりません。

3. プライバシーセキュリティ
本ソフトウェアには、クラッシュ情報の報告や本ソフトウェア内の使用データのアップロードを除いて、ユーザーの端末データを破壊したり、ユーザーのプライバシー情報を取得したりする悪意のあるコードは含まれていません。
ユーザーの端末の行動を追跡、監視する機能コードは含まれておらず、ユーザーのオンラインまたはオフラインの行動を監視することはありません。他のソフトウェアや文書などの個人情報を収集することはなく、ユーザーのプライバシーを漏洩することもありません。
収集されたデータは、ユーザーがクラッシュ中のエラー情報を分析し、本ソフトウェアを改善するために使用されます。
以下は使用している統計データ開発ツールです：
  Ⅰ. 使用SDK名：友盟SDK
  収集される個人情報の種類：デバイス情報（IMEI/Mac/android ID/IDFA/OPENUDID/GUID/SIMカードIMSI/地理位置情報）
  サービスの種類：データ収集と統計分析''',
  'privacy_umeng': '《友盟プライバシーポリシーリンク》',
  'privacy_detail2': '''
\nⅡ. 使用SDK名：MobTechのShareSDK
  サービスの種類：シェアとプッシュを実現''',
  'privacy_share': '《MobTechプライバシーポリシーリンク》',
  'privacy_detail3': '''
\nⅢ. 使用SDK名：360加固SDK（APK/HAP/APKプラグイン/SDK加固に適用）
  デバイス権限：なし
  実現する機能目的：アプリの故障検出と診断、アプリのセキュリティ強化保護、海賊版検出サービス、脅威環境検出サービスを提供し、ユーザーが異常な状況を迅速に解決できるようにする
  権限付与方法：権限付与方法はアプリ開発者が決定します。端末ユーザーが開発者のアプリに権限を付与することに同意した場合に有効になります''',
  'privacy_360': '《360加固プライバシーポリシーリンク》',
  'privacy_detail4': '''
\n\n4. ユーザーへの注意
本ソフトウェアはLoveLive!ファンによって自主的に使用されており、著作権のある曲は含まれていません。著作権のある曲はユーザーが自らCDから抽出してインポートする必要があります。インポートのディレクトリ構造はGithubプロジェクトの文書を参照してください。
ユーザーは法律および契約に従って本ソフトウェアを使用する必要があります。ユーザーは以下の行為を行う権利を有しません：
Ⅰ. 本ソフトウェアのすべての権利管理電子情報を削除または変更してはなりません；
Ⅱ. 本ソフトウェアを利用して他人を誤解させ、欺いてはなりません；
Ⅲ. 国家の規定に違反して、コンピュータ情報システムの機能を削除、変更、追加、干渉し、コンピュータ情報システムが正常に動作できなくなる原因を作ってはなりません；
Ⅳ. 許可なくコンピュータ情報ネットワークにアクセスしたり、コンピュータ情報ネットワーク資源を使用したりしてはなりません；
Ⅴ. 許可なくコンピュータ情報ネットワークの機能を削除、変更、または追加してはなりません。
  ''',
  'now_playing': '再生中：',
  'group_list': 'グループリスト',
  'back': '戻る',
  'phone': 'スマートフォン',
  'pc': 'PC',
  'add_favorite_menu': 'お気に入りのプレイリスト',
  'music_blind_box': '音楽ブラインドボックス',
  'throbbing': 'あなたがドキドキするのはわかりますが、交通安全にも注意してください',
  'exit': '終了',
  'finish': '完了',
  'search_in_moe_girl': '萌娘百科で検索',
  'share_error': '共有に失敗しました。エラーコード：',
  'share_success': '成功を分かち合います',
  'share_cancel': 'キャンセルを共有します',
  'daily_news': '日々のニュース',
  'recent_trends': '最近のトレンド',
  'live_notice': '放送予告',
  'today_in_previous_years': '過去の今日',
  'input_song_main_char': '曲名のキーワードを入力してください',
  'playing': '放送中',
  'paused': '停止しました'
};
